services:
  gaps-dev:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:22222:22
    volumes:
      - ../../:/home/ubuntu/gaps:ro
    runtime: nvidia
    # 64 MiB
    shm_size: 67108864
