services:
  shoi:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:22222:22
    volumes:
      - ../../:/home/ubuntu/shoi:ro
    runtime: nvidia
    # 256 MiB
    shm_size: 268435456
