services:
  dev:
    build:
      context: .
      args:
        - IMG=${IMG}
    restart: unless-stopped
    ports:
      - 127.0.0.1:22222:22
    volumes:
      - ../:/home/ubuntu/shoz
    runtime: nvidia